In [1]:
# San Francisco Crime Data Analysis

## Objective
#This report analyzes crime data from San Francisco to identify:
#- The most common crime categories
#- Crime distribution by district
#- Crime patterns by time of day

#Data Source: Kaggle SF Crime Classification Dataset
#Tools Used: PostgreSQL, SQL, Python (Pandas, Matplotlib, Seaborn)

In [2]:
import pandas as pd
import psycopg2

conn = psycopg2.connect(
    dbname="sfcrime",
    user="lilianaconstantino",
    host="localhost"
)

In [3]:
query = """
SELECT *
FROM train
LIMIT 10;
"""

pd.read_sql(query, conn)

/var/folders/vd/sgjg7qx50vd24t4qbpmz_nqc0000gn/T/ipykernel_2078/4205502585.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

,id,dates,category,descript,dayofweek,pd_district,resolution,address,x,y
0,1,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
1,2,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
2,3,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414
3,4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873
4,5,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541
5,6,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM UNLOCKED AUTO,Wednesday,INGLESIDE,NONE,0 Block of TEDDY AV,-122.403252,37.713431
6,7,2015-05-13 23:30:00,VEHICLE THEFT,STOLEN AUTOMOBILE,Wednesday,INGLESIDE,NONE,AVALON AV / PERU AV,-122.423327,37.725138
7,8,2015-05-13 23:30:00,VEHICLE THEFT,STOLEN AUTOMOBILE,Wednesday,BAYVIEW,NONE,KIRKWOOD AV / DONAHUE ST,-122.371274,37.727564
8,9,2015-05-13 23:00:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,RICHMOND,NONE,600 Block of 47TH AV,-122.508194,37.776601
9,10,2015-05-13 23:00:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,CENTRAL,NONE,JEFFERSON ST / LEAVENWORTH ST,-122.419088,37.807802

In [4]:
query = """
SELECT COUNT(*) AS total_records
FROM train;
"""

pd.read_sql(query, conn)

/var/folders/vd/sgjg7qx50vd24t4qbpmz_nqc0000gn/T/ipykernel_2078/923254866.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   total_records
0         878049

In [5]:
# Top Crime Categories

In [6]:
query = """
SELECT category, COUNT(*) AS crime_count
FROM train
GROUP BY category
ORDER BY crime_count DESC;
"""

top_crimes = pd.read_sql(query, conn)
top_crimes

/var/folders/vd/sgjg7qx50vd24t4qbpmz_nqc0000gn/T/ipykernel_2078/1650885851.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  top_crimes = pd.read_sql(query, conn)

                       category  crime_count
0                 LARCENY/THEFT       174900
1                OTHER OFFENSES       126182
2                  NON-CRIMINAL        92304
3                       ASSAULT        76876
4                 DRUG/NARCOTIC        53971
5                 VEHICLE THEFT        53781
6                     VANDALISM        44725
7                      WARRANTS        42214
8                      BURGLARY        36755
9                SUSPICIOUS OCC        31414
10               MISSING PERSON        25989
11                      ROBBERY        23000
12                        FRAUD        16679
13       FORGERY/COUNTERFEITING        10609
14              SECONDARY CODES         9985
15                  WEAPON LAWS         8555
16                 PROSTITUTION         7484
17                     TRESPASS         7326
18              STOLEN PROPERTY         4540
19        SEX OFFENSES FORCIBLE         4388
20           DISORDERLY CONDUCT         4320
21                  DRUNKENNESS         4280
22            RECOVERED VEHICLE         3138
23                   KIDNAPPING         2341
24  DRIVING UNDER THE INFLUENCE         2268
25                      RUNAWAY         1946
26                  LIQUOR LAWS         1903
27                        ARSON         1513
28                    LOITERING         1225
29                 EMBEZZLEMENT         1166
30                      SUICIDE          508
31              FAMILY OFFENSES          491
32                   BAD CHECKS          406
33                      BRIBERY          289
34                    EXTORTION          256
35    SEX OFFENSES NON FORCIBLE          148
36                     GAMBLING          146
37      PORNOGRAPHY/OBSCENE MAT           22
38                         TREA            6

In [24]:
top_crimes.to_csv("top_crimes.csv", index=False)

In [8]:
# Crime distribution by Police District

In [9]:
query = """
SELECT pd_district, COUNT(*) AS crime_count
FROM train
GROUP BY pd_district
ORDER BY crime_count DESC;
"""

district_crime = pd.read_sql(query, conn)
district_crime

/var/folders/vd/sgjg7qx50vd24t4qbpmz_nqc0000gn/T/ipykernel_2078/1704214705.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  district_crime = pd.read_sql(query, conn)

  pd_district  crime_count
0    SOUTHERN       157182
1     MISSION       119908
2    NORTHERN       105296
3     BAYVIEW        89431
4     CENTRAL        85460
5  TENDERLOIN        81809
6   INGLESIDE        78845
7     TARAVAL        65596
8        PARK        49313
9    RICHMOND        45209

In [22]:
district_crime.to_csv("crime_by_district.csv", index=False)

In [11]:
# Crime by Day of Week

In [12]:
query = """
SELECT dayofweek, COUNT(*) AS crime_count
FROM train
GROUP BY dayofweek
ORDER BY crime_count DESC;
"""

crime_by_day_of_week = pd.read_sql(query, conn)
crime_by_day_of_week

/var/folders/vd/sgjg7qx50vd24t4qbpmz_nqc0000gn/T/ipykernel_2078/1980156019.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  crime_by_day_of_week = pd.read_sql(query, conn)

   dayofweek  crime_count
0     Friday       133734
1  Wednesday       129211
2   Saturday       126810
3   Thursday       125038
4    Tuesday       124965
5     Monday       121584
6     Sunday       116707

In [23]:
crime_by_day_of_week.to_csv("crime_by_day_of_week.csv", index=False)

In [14]:
# Crime by Hour of Day

In [15]:
query = """
SELECT EXTRACT(HOUR FROM dates) AS hour, COUNT(*) AS crime_count
FROM train
GROUP BY hour
ORDER BY hour;
"""


crime_by_hour_of_day = pd.read_sql(query, conn)
crime_by_hour_of_day

/var/folders/vd/sgjg7qx50vd24t4qbpmz_nqc0000gn/T/ipykernel_2078/152749457.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  crime_by_hour_of_day = pd.read_sql(query, conn)

    hour  crime_count
0    0.0        44865
1    1.0        26173
2    2.0        22296
3    3.0        14014
4    4.0         9863
5    5.0         8637
6    6.0        13133
7    7.0        22048
8    8.0        32900
9    9.0        35555
10  10.0        37806
11  11.0        38373
12  12.0        51934
13  13.0        43145
14  14.0        44424
15  15.0        48058
16  16.0        50137
17  17.0        53553
18  18.0        55104
19  19.0        49475
20  20.0        44694
21  21.0        43661
22  22.0        45741
23  23.0        42460

In [16]:
crime_by_hour_of_day.to_csv("crime_by_hour_of_day.csv", index=False)

In [17]:
# Day + Hour + Crime count

In [18]:
query = """
SELECT 
    dayofweek,
    EXTRACT(HOUR FROM dates) AS hour,
    COUNT(*) AS crime_count
FROM train
GROUP BY dayofweek, hour
ORDER BY dayofweek, hour;
"""

df = pd.read_sql(query, conn)

df.head()

/var/folders/vd/sgjg7qx50vd24t4qbpmz_nqc0000gn/T/ipykernel_2078/3164909966.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

  dayofweek  hour  crime_count
0    Friday   0.0         6459
1    Friday   1.0         3429
2    Friday   2.0         2972
3    Friday   3.0         1831
4    Friday   4.0         1326

In [19]:
df.to_csv("crime_by_day_hour.csv", index=False)